ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_interaction_epoch_ms BIGINT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS total_session_wall_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_gap_duration_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS perceived_weight REAL NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS drift REAL NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS passive_processing_strength REAL NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS discovery_queue_json TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS learned_facts_json TEXT;
